// packages/onequote-react/app/components/md-wrapper.tsx
import type { ReactNode } from 'react'
import mediumZoom from 'medium-zoom'
import { useEffect } from 'react'
import { useLocation } from 'react-router'
import { formatDate } from '~/logics'
import Back from './back'

interface MdxFrontmatter {
  title: string
  date?: string
  description?: string
  [key: string]: any
}

interface MdxWrapperProps {
  children: ReactNode
  frontmatter: MdxFrontmatter
}

// set meta for the wrapper itself, it will be merged with the meta from mdx file
export function meta({ frontmatter }: { frontmatter: MdxFrontmatter }) {
  return [
    { title: frontmatter.title },
  ]
}

export default function MarkdownWrapper({ children, frontmatter }: MdxWrapperProps) {
  const currentPath = useLocation().pathname

  useEffect(() => {
    const zoom = mediumZoom('.prose img', {
      background: 'rgba(0, 0, 0, 0.75)',
      margin: 24,
      scrollOffset: 0,
    })
    return () => {
      zoom.detach()
    }
  }, [])

  return (
    <div className="prose">
      {frontmatter.title && (
        <h1 id={frontmatter.title} className="mb-0">
          {frontmatter.title}
        </h1>
      )}
      {frontmatter.date || frontmatter.description
        ? (
            <div className="opacity-50 !-mt-6">
              {frontmatter.description && <span>{frontmatter.description}</span>}
              {frontmatter.date && <span>{`-${formatDate(frontmatter.date, false)}`}</span>}
            </div>
          )
        : null}
      <article className="post relative">
        {/* MDX content will be rendered here */}
        {children}
      </article>
      <span className="font-mono op50">&gt; </span>
      {currentPath !== '/' && <Back />}
    </div>
  )
}

// packages/onequote-vue/src/components/MdWrapper.vue
<template>
  <div class="prose">
    <h1 v-if="frontmatter.title" :id="frontmatter.title" class="mb-0">
      {{ frontmatter.title }}
    </h1>
    <div v-if="frontmatter.date || frontmatter.description" class="opacity-50 !-mt-6">
      <span v-if="frontmatter.description">{{ frontmatter.description }}</span>
      <span v-if="frontmatter.date">{{ `-${formatDate(frontmatter.date, false)}` }}</span>
    </div>
    <div class="prose relative">
      <slot />
    </div>
    <span class="font-mono op50">&gt; </span>
    <Back v-if="route.path !== '/'" class="font-mono op50 hover:op75" />
  </div>
</template>

<script setup lang="ts">
import mediumZoom from 'medium-zoom'
import { formatDate } from '@/logics'

interface Frontmatter {
  title?: string
  description?: string
  date?: string
  [key: string]: unknown
}

const { frontmatter } = defineProps<{
  frontmatter: Frontmatter
}>()

const route = useRoute()

const zoomRef = ref()
onMounted(() => {
  zoomRef.value = mediumZoom('.prose img', {
    background: 'rgba(0, 0, 0, 0.75)',
    margin: 24,
    scrollOffset: 0,
  })
})
onUnmounted(() => {
  zoomRef.value?.detach()
})
</script>
