// packages/onequote-react/app/routes/app.tsx
import type { Route } from './+types/app'
import { Outlet } from 'react-router'
import Footer from '~/components/footer'
import Header from '~/components/header'

export function meta({}: Route.MetaArgs) {
  return [
    { title: 'OneQuote-React' },
  ]
}

export default function App() {
  return (
    <div className="app-container">
      <Header />
      <main className="body-content">
        <Outlet />
      </main>
      <Footer />
    </div>
  )
}

// packages/onequote-vue/src/App.vue
<template>
  <div class="app-container">
    <Header />
    <main class="body-content">
      <RouterView />
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { RouterView } from 'vue-router'
import Footer from '@/components/Footer.vue'
import Header from '@/components/Header.vue'
</script>
